### ISSUE TITLE
这个SD的API支持云端部署的SD吗

### ISSUE THREAD

**Issue by ChangqingQ11** [cssxsh/stable-diffusion-helper#1]
感谢大佬

**Comment by cssxsh** [comment]
https://github.com/cssxsh/stable-diffusion-helper#%E9%85%8D%E7%BD%AE

**Comment by cssxsh** [comment]
`云端部署` 这个描述过于模糊

**Comment by ChangqingQ11** [comment]
> `云端部署` 这个描述过于模糊

就和大佬您之前的Novelai-helper一样，是否可以支持colab之类的云端平台部署的webUI呢？

**Comment by cssxsh** [comment]
记得开 API模式就行
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API
