### ISSUE TITLE
sampler_name参数问题

### ISSUE THREAD

**Issue by Joel0495** [cssxsh/stable-diffusion-helper#5]
sampler_name好像不支持空格？使用"x x x x"也不行，输入sampler_name=Euler a在I/StableDiffusionListener里会直接变成Euler

**Comment by cssxsh** [comment]
之前的 commit 已经处理
https://github.com/cssxsh/stable-diffusion-helper/commit/0746af0d32581a6bddeaa6fe15d6a6aeb0982ff3

你可以先下载 actions 中构建的版本
https://github.com/cssxsh/stable-diffusion-helper/actions/runs/4371746780

**Comment by Joel0495** [comment]
非常感谢！加引号就可以直接使用了，还有@功能，nice！
