### ISSUE TITLE
sample参数中存在空格判定错误的情况

### ISSUE THREAD

**Issue by Cha-Sir** [cssxsh/stable-diffusion-helper#6]
如
t2i 
steps=50
width=360
height=540
sampler_name=DPM++ 2S a Karras
night, rain, wet

后台会判定为采样器名为”DPM++"然后报错，其他带有空格的采样器名也会如此

**Comment by cssxsh** [comment]
https://github.com/cssxsh/stable-diffusion-helper/issues/5
