### ISSUE TITLE
Hires. fix 开启失败

### ISSUE THREAD

**Issue by Happylinzy** [cssxsh/stable-diffusion-helper#7]
问题：开启了Hires.fix但是实际上生成图片并没有高清修复。
并且声称的速度也是和没有开启高清修复的版本相同。
并且同样的prompt在webui中跑出来的效果会更高清

参数命令：

t2i 27671231
steps=40
width=512
height=512
hr_second_pass_steps = 0
denoising_strength = 0.7
hr_upscaler = Latent
hr_scale  = 2.0
enable_hr = true
((masterpiece)),((best quality)),((high detial)),((realistic,)) Industrial age city, deep canyons in the middle, architectural streets, bazaars, Bridges, rainy days, steampunk, European architecture
#neg_normal

**Comment by cssxsh** [comment]
你似乎加了很多空格
